### ISSUE TITLE
DisplayName is null after registration

### ISSUE THREAD

**Issue by thinh-mazeika** [chingu-voyages/v21-geckos-team-02#44]
But it's normal if you refresh the page.

**Comment by clarkj99** [comment]
This is how the `authUser` is updated.
```
useEffect(() => {
    firebase.auth.onAuthStateChanged((authUser) => {
      setAuthUser(authUser);
    });
  }, [firebase.auth]);
```
A new user is created in one step in firebase.js. Then the displayName is updated in another.  The listener only responds when a user is created or logged in, not when updated.

We need to 
1. handle `setAuthUser` in **AuthUserContext.js**
1. include `setAuthUser` as the second parameter in `firebase.doCreateUserWithEmailAndPassword()` call in **SignUpForm/form.js**
1. Call `setAuthUser` in promise chain after the auth is created in **firebase.js**
1. change `authUser=useContext(AuthUserContext)` to `{authUser}=useContext(AuthUserContext)` everywhere.
